[package]
name = "io"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
log = { workspace = true }
uuid = { workspace = true }
tokio-stream = "0.1"
zip = "0.6"
tar = "0.4"
flate2 = "1.0"
